# Generated by Django 3.2 on 2023-08-21 07:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HotArticleModel',
            fields=[
                ('id', models.CharField(blank=True, max_length=13, primary_key=True, serialize=False, verbose_name='文章編號')),
                ('date', models.DateField(verbose_name='文章日期')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='標題')),
                ('content', models.TextField(blank=True, max_length=300, verbose_name='內容')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover', verbose_name='封面照片')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='內部照片')),
                ('url', models.URLField(blank=True, max_length=50, verbose_name='頁面連結')),
                ('valid', models.BooleanField(blank=True, default=True, verbose_name='是否有效')),
                ('latest_edit_date', models.DateTimeField(auto_now_add=True, verbose_name='最後編輯日期')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='最後編輯者')),
            ],
        ),
        migrations.CreateModel(
            name='RankArticleModel',
            fields=[
                ('rank_id', models.CharField(blank=True, max_length=16, primary_key=True, serialize=False, verbose_name='排名編號')),
                ('rank', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='排名')),
                ('title', models.CharField(blank=True, max_length=30, verbose_name='標題')),
                ('content', models.TextField(blank=True, max_length=300, verbose_name='內容')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='related_pic', verbose_name='相關照片')),
                ('url', models.URLField(blank=True, max_length=50, null=True, verbose_name='延伸閱讀連結')),
                ('url_title', models.CharField(blank=True, max_length=30, null=True, verbose_name='延伸閱讀標題')),
                ('hot_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotArticle.hotarticlemodel')),
            ],
        ),
    ]
